[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"

size = 16

[keyboard] 
bindings = [
  { key = "NumpadEnter", chars = "\r" },
  { key = "Back", mods = "Command", chars = "\u0015"},
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "Back", mods = "Alt", chars = "\u001B\u007F" },  
]

[general]
import = [
  "~/.config/alacritty/themes/rose-pine.toml"
]
